import {
  Dashboard,
  MeetingRoom,
  HowToReg,
  PlaylistAdd,
  FolderOpen,
  MonitorHeart,
  Assignment,
  CalendarMonth,
  FactCheck,
  Favorite,
  KingBed,
  Description,
  Receipt,
  MedicalServices,
  VerifiedUser,
  ContentCut,
  Inventory,
  Inventory2,
  NoteAdd,
  Sell,
  CheckCircle,
  ShoppingCart,
  LocalShipping,
  Warehouse,
  AllInbox,
  Send,
  Replay,
  TravelExplore,
  BarChart,
  ContactPage,
  Groups,
  Person,
  AttachMoney,
  Settings,
  WarningAmber,
} from '@mui/icons-material'

const MENU_ICON_MAP = {
  Dashboard,
  DoorOpen: MeetingRoom,
  UserCheck: HowToReg,
  ClipboardPlus: PlaylistAdd,
  FolderOpen,
  Activity: MonitorHeart,
  ClipboardList: Assignment,
  CalendarDays: CalendarMonth,
  FileCheck: FactCheck,
  HeartPulse: Favorite,
  BedDouble: KingBed,
  FileText: Description,
  Receipt,
  Stethoscope: MedicalServices,
  ShieldCheck: VerifiedUser,
  Scissors: ContentCut,
  PackageCheck: Inventory,
  Boxes: AllInbox,
  FilePlus: NoteAdd,
  BadgeDollarSign: Sell,
  CheckCircle2: CheckCircle,
  ShoppingCart,
  Truck: LocalShipping,
  Warehouse,
  Package: Inventory2,
  Send,
  RotateCcw: Replay,
  ScanSearch: TravelExplore,
  BarChart3: BarChart,
  BarChart2: BarChart,
  BookUser: ContactPage,
  Users: Groups,
  User: Person,
  DollarSign: AttachMoney,
  Settings,
  Alert: WarningAmber,
}

export const getMenuIcon = (iconName) => MENU_ICON_MAP[iconName] || Dashboard
